/*
 * This file is generated by jOOQ.
 */
package app.jooq;


import app.jooq.tables.Author;
import app.jooq.tables.Books;
import app.jooq.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>library</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUTHOR_PRIMARY = Indexes0.AUTHOR_PRIMARY;
    public static final Index BOOKS_AUTHOR_ID = Indexes0.BOOKS_AUTHOR_ID;
    public static final Index BOOKS_PRIMARY = Indexes0.BOOKS_PRIMARY;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AUTHOR_PRIMARY = Internal.createIndex("PRIMARY", Author.AUTHOR, new OrderField[] { Author.AUTHOR.ID }, true);
        public static Index BOOKS_AUTHOR_ID = Internal.createIndex("author_id", Books.BOOKS, new OrderField[] { Books.BOOKS.AUTHOR_ID }, false);
        public static Index BOOKS_PRIMARY = Internal.createIndex("PRIMARY", Books.BOOKS, new OrderField[] { Books.BOOKS.ISBN }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.USERNAME }, true);
    }
}
