/*
 * This file is generated by jOOQ.
 */
package app.jooq;


import app.jooq.tables.Author;
import app.jooq.tables.Books;
import app.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in library
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.author</code>.
     */
    public static final Author AUTHOR = app.jooq.tables.Author.AUTHOR;

    /**
     * The table <code>library.books</code>.
     */
    public static final Books BOOKS = app.jooq.tables.Books.BOOKS;

    /**
     * The table <code>library.user</code>.
     */
    public static final User USER = app.jooq.tables.User.USER;
}
